denolib/awesome-deno

README.md
Add a Japanese translation of "10 Things I Regret About Node.js"
=> Add Japanese Resource

README.md
=> chore: Add wu-diff-js

README.md
Adds [deno-postgres](https://github.com/bartlomieju/deno-postgres) to README
=> add deno-postgres

README.md
Fixes olivewind/awesome-deno#7.
=> To add new library

README.md
I made denoland for Korean to provide materials and docs translated in Korean
=> Add denoland for Korean

README.md
Add Japanese articles which describes about Deno internals.
=> Add some Japanese articles

README.md
=> Add deno-uuid

README.md
Repo - https://github.com/luvies/lazy
Registry - https://deno.land/x/lazy@{tag}/mod.ts
=> Added lazy module

README.md
Add Chinese Learning Documents
=> docs: add deno_note

README.md
=> Add deno-using

README.md
[sax-ts](https://github.com/Maxim-Mazurok/sax-ts) - SAX-style XML parser ported from [sax-js](https://github.com/isaacs/sax-js)
=> Added sax-ts

README.md
Add Chinese translations of "deno manual" and "deno style guide"
=> Add Chinese Resource

README.md
=> Add deno-fen

README.md
=> add typescript-deno-plugin

README.md
=> Add `expect` module

README.md
=> Add `cac` module

README.md
=> Add `servest` module

README.md
dso - Simple Deno ORM library
sql-builder - sql query builder
=> add modules

README.md
Got jwt working with jsrsasign. It's supposed to be slow and will move to native crypto/signing once available.
=> docs: add jwt

README.md
Gardens is a logging utility I made with the goal of being able to run it everywhere. Deno has recently become a compatibility target for Gardens as I've had more of a desire to tinker with it lately, and all of my tests are passing in Deno as of this morning.
=> Add gardens to the list

README.md
These depend on too old versions of Deno and don't seem maintained.
=> Remove fen and expressive

README.md
I added it because it seems to have no presentation.
=> Add presentation

README.md
https://github.com/timonson/djwt
=> Added the repository djwt to the modules list

README.md
https://github.com/OnikurYH/deno-prettystring
This module is for format, trim and remove extra white spaces between characters from string.
=> Add “deno-prettystring” module

README.md
I added three links to articles for beginners (disclaimer: I'm the author of the third one)
=> Add new articles and tutorials

README.md
https://github.com/axetroy/dvm
=> add another dvm for tool chain

README.md
Repository: https://github.com/eliassjogreen/denon/
Added both to tools and modules due to it also exporting a file watcher generator.
=> Added denon tool and module

README.md
Video: https://www.youtube.com/watch?v=1gIiZfSbEAE
=> add presentation from TSConf 2019

README.md
New article on Deno written by me.
=> Added New Article

README.md
I think these are both relatively popular and makes sense to reference both.
?
=> Add in another popular docker image repo

README.md
add mongodb driver
add plugin-prepare module
=> add mongodb driver

README.md
https://github.com/hayd/deno-udd
=> Add udd to tools - Update Deno Dependencies

README.md
https://github.com/timonson/gentleRpc
=> Added gentleRpc

.github/workflows/ci.yml, README.md
Named it webview to match deno.land/x/webview
=> Added deno_webview

README.md
=> Add denoify and EVT

README.md
=> Add deno-express

README.md
And remove deno_init (it has been deprecated
=> add dev_server

README.md
- The title need to be `Awesome Deno` to follow [the guidline](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md).
- The CI badge shouldn'be there to follow [the guidline](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md).
=> Misc changes to follow the guideline

README.md
Hai, Thanks for this awesome repo, I added an article for Bahasa Indonesia, thanks
=> Added an article in Bahasa Indonesia

README.md
=> Add unexpectedjs/unexpected

README.md
=> Add an article

README.md
The publication is my authorship in Medium, I would like to add it for Spanish-speaking people
=> Add a Hello World post in Deno in Spanish

README.md
[Denoliver](https://github.com/joakimunge/denoliver)
Denoliver is a simple, dependency free, static file server with live reload and client routing support that I created. I hope you like it :)
=> Add Denoliver - A dependency free file server

README.md
HTTP codes and status utility for Deno. Based on Java Apache HttpStatus
=> Add `status` module

README.md
add this module https://deno.land/x/context
thanks.
=> added code-hex/deno-context

README.md
This PR adds a few packages :)
=> Add Denorg packages

README.md
A Deno client library for the YouTube Data API V3. Lets you incorporate core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and almost any interaction with YouTube from your Deno app. 
Link to Deno third party location: https://deno.land/x/youtube_deno
=> Add youtube-deno

README.md
This PR adds the following new module:
- <https://github.com/asos-craigmorten/opine>
`Opine` is a fast, minimalist web framework for Deno ported from ExpressJS.
The module is a like-for-like port of ExpressJS - in essence a fork, however it was easier to build it from the ground up due to the significant number of changes and rewrites needed in order to support the Deno `import` syntax, types, the new Deno API etc.
I have started this project as I felt that the current "ExpressJS inspired" Deno modules are somewhat lacking in either support, features / API, and none of these packages truly mirror how the ExpressJS internals work - if you are aware of such a project then I will happily drop this module in support of contributing to it!
And why this project is different:
- …
=> [Module Request] Opine - a fast, minimalist web framework ported from ExpressJS

README.md
https://github.com/jeferson-sb/deno-notes-cli
=> Add article: Create a Note-taking app with Deno

README.md
@kevinkassimo review please
<details>
添加中文开发者社区，基于 discourse  搭建的论坛。
</details>
=> add "Deno Chinese Developer Community"

README.md
There exists a lot of people who can't understand English even if it's internation language. We took the original website and translated it to uzbek and credited to original site with author. Thanks for your attention)
=> added translated website

README.md
I have added **deno_cron** a job scheduler module to the List. I would be grateful if you please merge my changes. Thanks
=> Added deno_cron to the module list

README.md
=> add wasm-gzip module

README.md
=> Removed Newsletter because it's not updated

README.md
https://github.com/divy-work/autopilot-deno
Thank you!
=> Add `autopilot` to Readme

README.md
* Add Contents 'Italian' section item
* Add italian section
* Add first italian talk slides named: Deno - L'anagramma di Node
=> Add Italian section w/ talk slides

README.md
Adds:
- [DenoBeginner.com](https://DenoBeginner.com) - A completely free crash course on deno for beginners.
P.S. Thanks for the awesome resource.
=> 📦 NEW: Free course

README.md
🔥 NEW SECTION: Projects
Showcase open-source projects built using Deno. 
ADD: 1st project built fully powered by deno: https://usingdeno.com
=> 🔥 NEW SECTION: Projects & 1st Project

README.md
Here are two tools I am developing for Deno and a post I made in Spanish on dev.to
=> two tools and a post on spanish.

README.md
https://github.com/denoland/deno_website2/issues/1104
https://github.com/replit/polygott/issues/62
=> added: repl.it deno online playground

README.md
tiny library to manage environment variables with deno.
=> add dinoenv

README.md
[ts-prometheus](https://github.com/marcopacini/ts-prometheus) is a prometheus client in Typescript that provide `Counter`, `Gauge` and `Histogram` metrics.
=> Add ts-promethus to modules

README.md
This PR adds a section to the README called `registries`. As an author of https://nest.land, I think it would be great to see this registry added to awesome-deno!
=> New "Registries" section & nest.land listing

README.md
Include [microraptor](https://github.com/matteocrippa/microraptor) a lightweight network route/validator I start building to mimic a lean structure I quite use with expressjs in my normal day node projects.
=> Adds microraptor

README.md
Fossil introduce an easy type and value based suite of validations tools.
It support basic typescript type and allow an extra custom `function` to handle easily edge cases.
=> adds fossil

README.md
I created a Github Action to be able to keep track of the latest Deno version.
This will auto update your repo with the latest Deno version, stored in a file.
=> Add Update Deno

README.md
Created as a means to learn about running functions in containers, and refreshing my Deno knowledge (and to be able to deploy this on my file server), I've been tinkering on this little project.
https://github.com/jeroenptrs/denoFn
Just a `docker-compose up` and you should be able to run your functions in a container.
=> Add denoFn

README.md
https://github.com/drashland/dmm
Add dmm
Dmm is a very lightweight module manager. No configuration files, no setup, and a simple read and write to your dependency files
=> Added dmm to modules

README.md
[coffee](https://github.com/irandeno/coffee) is the first configuration manager on the list.
=> add coffee to modules

README.md
=> reopen deno.js.cn

README.md
add doa to modules, thanks team. ❤️
=> Add doa to modules

README.md
[Denodb](https://github.com/eveningkid/denodb) is an ORM module for MySQL, SQLite, MariaDB, PostgreSQL and MongoDB
=> Add denodb to modules

README.md
https://deno.land/x/garn_validator@v1.3.6
=> Add garn-validator

README.md
In this article, there is a step by step guide for creating and validating JWT in Deno
=> Added article for using JWT token in Deno

README.md
[superoak](https://github.com/asos-craigmorten/superoak) - HTTP assertions for Oak made easy via SuperDeno.
=> Add superoak

README.md
**Regression**
- Added Deno Articles in ReadMe
- Formatted Few sentences
**Risk Impack**
Very Low
=> Added Deno Articles in ReadMe

README.md
In this article, there is a step by step guide for how to read and write in a local file in Deno
=> Added article to read and write in a file in Deno

README.md
plaese check https://github.com/postui/aleph.js or https://alephjs.org
=> Add Aleph.js module

README.md
The Hidden Superpower of Deno: xeval – https://stefanbuck.com/blog/hidden-superpower-deno-xeval
Please feel free to reject if you think this is not awesome enough.
=> Add new article about xeval

README.md
read or write yaml **interpolating env variables**
=> Add Garn-yaml

README.md
Add new boilerplate for RESTful apis based on oak, deno_mongo, god_crypto, cors, djwt and yup
=> Add Deno Rest to showcases

README.md
Let me know if I miss anything.
=> Add decense

README.md
**Link**: https://v1rtl.site/blog/coverage-in-deno
**Summary**: This article shows how to easily set up a toolchain for running tests, generating coverage and reporting it online using `deno test`, `deno coverage`, GitHub Actions and Codecov
=> Add "Test coverage in Deno with Codecov and GitHub Actions" to "Articles" section

README.md
=> fix MD typo

README.md
Btw, website will be fixed soon!
=> Fixed the uzbek community link

README.md
Hello! [AuthCompanion](https://github.com/pmprosociety/authcompanion) is an effortless, open source, token-based user management server made for microservices and static website projects.
Thanks for the consideration.
=> add 'authcompanion'

README.md
Adding new articles, will be worth while for new readers.
=> Added new articles in Readme

README.md
Include https://github.com/jacoborus/deno-buckets in the utils section.
=> Add buckets

README.md
Added https://github.com/matmen/ImageScript
JavaScript image manipulation utilizing WebAssembly and direct buffer access for performance
Works in Node, Deno and all modern browsers
If this should go into an already existing category instead of creating a new one, please let me know.
Cheers!
=> Add ImageScript

README.md
**Link**: https://github.com/deno-web3/solc
**Description**: Solidity bindings for Deno, based on solc-js.
=> Add solc to "Utils"

README.md
This implements [pre-commit](https://pre-commit.com/) git hooks for Deno projects.
Thank you for maintaining an awesome list!😃
=> add pre-commit-deno

README.md
Hi, Thanks for maintaining such a great list.
[Denoflow](https://github.com/denoflow/denoflow) is a configuration as code tool, you can use YAML to write automated workflows that run on Deno, with any Deno modules, Typescript/Javascript codes.
If there is anything that needs to be modified, please let me know, thanks!
=> Add denoflow

README.md
just a proxy for GitHub/GitLab repositories with caching
=> add denopkg.dev

README.md
Modular framework for building native multi-platform apps with Deno and  webview.
=> Adding Astrodon

README.md
GitHub
https://github.com/truestamp/truestamp-canonify
Deno
https://deno.land/x/canonify
=> Add canonify utility library

README.md
This PR adds a super tiny module I've created to introduce functional style error handling to Deno.
I've added it to the utils section, but if anyone can recommend a better section I'm all for it.
You can find it [here](https://github.com/twilsoft/tryify).
Thanks for your consideration!
=> Adds tryify error handling module to utilities section.

README.md
Fortuna is a weighted gacha system written in Typescript.
A guide for usage can be found in [docs.nekooftheabyss.moe](https://docs.nekooftheabyss.moe/fortuna)
=> Add fortuna

README.md
=> Add written

README.md
=> Add aws-api and googleapis

README.md
- [deno-validation](https://github.com/ethandunford/deno-validation) - A general purpose validation library for Deno.
=> deno validation

README.md
Hellooo 👋🏼 
This list is veeeeeeery awesome thanks for make this and here I add the libraries of the DPM Land Org 🦕
=> feat: add the dpmland org libraries to the awesome deno

README.md
Added link to my recently published book `Modern Web Development with Deno`
=> Add Resources/Books section

README.md
Added Blogs/Newsletters section with a few relevant links.
=> Added Blogs/Newsletters section

README.md
https://deno.land/x/tepi
Tepi is a test runner for .http files.
=> Add Tepi to testing

README.md
A color module for conversion and other color operations: https://github.com/retraigo/colors
=> Add retraigo/colors

README.md
https://github.com/retraigo/monke
Module for color quantization and dithering
=> Add retraigo/monke

README.md
Add a listing for locale-kit - a localisation library with support for soemwhat advanced string alteration depending on a key and arguments you pass in. It also has a Fresh integration
=> Add locale-kit

README.md
A blazing fast framework for the modern web.
🔗 [azurystudio/cheetah](https://github.com/azurystudio/cheetah)
closes #363
=> Add cheetah

README.md
https://github.com/retraigo/classy-lala
More models are being written now but currently it supports Linear and Logistic regression (both are stable).
=> Add classy-lala

README.md
Convert text into vectors:
https://github.com/retraigo/vectorizer
Currently supports a TS port of `CountVectorizer` and `TfIdfTransformer`.
=> Add vectorizer

README.md
Moving `monke` to **Image** from **Util**.
Removing `cubic-bezier` (no longer maintained).
=> Move monke, remove `cubic-bezier`

README.md
Adds [entype](https://github.com/bcheidemann/entype).
=> Add entype

README.md
=> Add SwissKnife

README.md
Alosaur had a big break. ES Decorators became available
=> Web framework: Alosaur
