denolib/awesome-deno

README.md
Some modules for Deno.
dpm - deno package manager, install global command for deno.
dcc - deno cache clean, reloading deps when next running.
=> add dpm, dcc

README.md
`normalize-diacritics` has been renamed to `normalize_diacritics` and moved to new repo.
=> Update module name and repo URL

README.md
To fix this CI error: 
```
1. [L030] 302 https://denolib.gitbook.io/guide  → https://denolib.gitbook.io/guide/
```
=> Fix guide URL

README.md
The link https://github.com/muhibbudins/marden is broken and the repository could no longer be found, causing travis failure.
cc @muhibbudins @hashrock
=> Remove module `marden`

README.md
deno-task-runner was moved to https://github.com/jinjor/deno-task-runner so it should not point redirection
=> update task-runner link so no redirect

README.md
This plugin is written in Go, but installs Deno on remote servers, and allows users to run a series of Deno scripts during their Packer build.
It also supports uploading test builds of Deno, for the case where the installer script cannot download an appropriate binary yet.
=> Add tool: packer-provisioner-deno

README.md
`colors` module has been moved under /std/fmt/ ( https://github.com/denoland/deno_std/pull/571 ), and now it doesn't have its own README. So I linked it to the page on deno.land.
=> Update colors url

README.md
Added note to notice that https://github.com/denolib/guide  is out of date.
=> Mark denolib.gitbook.io out dated

README.md
Like packages.json scripts, but for Deno with permissions hardcoded in a file.
```yaml
scripts:
start:
file: main.ts
permissions:
allow-net: example.com
develop:
file: main.ts
permissions:
allow-net: localhost
```
=> Add `denox` workspace wrapper around Deno

README.md
The cert expired on this page and it fails the CI. Removing it. Please re-add it if the problem fixed.
=> Remove https://adarshron.com/introducing-deno

README.md
- `database.json` seems having been moved. https://github.com/denoland/deno_website2/pull/408
=> Updata database.json path

.github/workflows/ci.yml
Allow 429 errors, do not have better solution.
https://github.com/dkhamsing/awesome_bot does not have issue feature activated. For the current state it fixes the CI.
=> fix: allow 429 errors

README.md
I'm adding more online playgrounds for deno, available here: https://deno-playground.now.sh
the repo is also available at [maman/deno-playground](https://github.com/maman/deno-playground)
=> Add playground link to deno-playground.now.sh

README.md
This adds the [ensure](https://github.com/eankeen/ensure) package to the list. I add it because it offers a very useful Deno equivalent to the popular [npm](https://www.npmjs.com/package/please-upgrade-node) 'please-upgrade-node' package. The package has passing unit and end to end tests.
=> add ensure package

README.md
Links to denon now point to the right repository and description are now relevant.
[`eliassjogreen/denon`](https://github.com/eliassjogreen/denon) is now [`denosaurs/denon`](https://github.com/denosaurs/denon)
=> fix: denon links and description

README.md
The [websocket_server](https://github.com/JohanWinther/websocket_server) package is a WebSocket server library.
It provides a server class which implements an asyncIterable instead of using the event/callback pattern (which [ryo-ma/deno-websocket](https://github.com/ryo-ma/deno-websocket) uses).
=> Add websocket_server

README.md
[deno_notify](https://github.com/PandawanFr/deno_notify) allows you to send desktop notifications on all platforms.  
It has already been added to deno.land/x so I just thought I'd add it do awesome-deno as well.
=> Add deno_notify

README.md
Given that MD5 and base hash functions are already supported as part of `std/hash` by now (https://github.com/denoland/deno/pull/5719) I think it's miss leading to recommend a third party module.
MD5 generation is nothing but - https://gist.github.com/AvnerCohen/d056dc1aedbf336f2df0bbed040b2d8e
So I suggest to instead recommend standard libs.
=> Remove md5 as a third party module

README.md
Adds [Create your first News CLI app using Deno](https://medium.com/javascript-in-plain-english/creating-your-first-news-cli-app-using-deno-e1470398c627) article.
This article is different as it covers most of the basic concepts of Deno, compares and contrasts the design choices of Deno with NodeJS, providing a better foundation for a Deno beginner.
=> Add article: Create your first News CLI app using Deno

README.md
This is a tutorial on getting started with Continuous Integration with Deno and using Docker to run your Deno applications.
Link: https://semaphoreci.com/blog/continuous-integration-with-deno
Title: Continuous Integration with Deno
I didn't find any other CI/CD articles on the list, so I think this may come in handy to anyone trying to deploy applications with Deno.
=> Add Article: Continuous Integration with Deno

README.md
Fixes #75 
https://github.com/drashland/deno-drash
Add Drash to the list of modules.
Drash is a fast (compared to other frameworks) HTTP microframework, with zero dependencies, the 4th most starred module on deno.land and faster than the Oak framework
=> Add Drash to Modules

README.md
https://github.com/ebebbington/deno-task-runner-v2
task-runner-v2 is supposed to be an updated version of https://github.com/jinjor/deno-task-runner, to fix issues around that repo as there are many, and the maintainer seems to have left it
=> Add task-runner-v2 to modules

README.md
https://github.com/ebebbington/deno-context-finder
Deno-Context-Finder is a module for a specific use case, to extract configuration blocks from a config file - usually for Asterisk conf blocks
Original built for someone in Node who had a usecase, then ported to Deno to cater to a wider audience
=> Add context-finder to modules

README.md
https://github.com/drashland/sockets
Adds sockets
Sockets is a WebSocket library for Deno, similar to Socket.io (boasting similar features/functionality/usage)
=> Added sockets to modules

README.md
https://github.com/drashland/rhum
Add Rhum to modules.
Rhum was the first testing framework developed, inspired by Mocha and Chai. Rhum is made with readability in mind, turning the usual test files and output into something much more readable and clean
=> Add Rhum to modules

README.md
I'm the owner of the denoserverless org and I've been doing some housekeeping in my repos. I recently renamed it to denofn, since I want to use the org to maintain [denoFn (now denofn-selfhosted)](https://github.com/jeroenptrs/denoFn). That has made me come to the conclusion that there's a ton of clutter on there that I added in this doc and I want to prevent devs that are new to Deno from using unmaintained software.
- jwt: djwt is maintained and works perfectly fine
- https-libs: all those dependencies can most likely be resolved via pika.dev/skypack
I already archived the repos but plan on removing them for the reasons listed above once they're out of this document.
=> Housekeeping: remove unmaintained repos

README.md
This PR adds [superdeno](https://github.com/asos-craigmorten/superdeno) - _Super-agent driven library for testing Deno HTTP servers_.
superdeno allows Deno programmers to test their HTTP servers in same way [supertest](https://github.com/visionmedia/supertest) does for Node packages.
=> Add superdeno to modules

README.md
[Eta](https://eta.js.org) is an embedded template engine similar to EJS and doT. It's very fast, configurable, and supports plugins. Examples of Deno projects using Eta exist for [Opine](https://github.com/asos-craigmorten/opine/tree/main/examples/eta) and [Alosaur](https://github.com/alosaur/alosaur/tree/master/examples/eta).
_Similar packages_
The two other template engines on the list are [dejs](https://github.com/syumai/dejs) and [deno_tiny_templates](https://github.com/zekth/deno_tiny_templates). Though these are cool modules, I think Eta is more powerful, more reliable, better tested, and has better documentation.
Thanks for creating this awesome repo!
=> Add Eta to the Modules section

README.md
[prettyBenching](https://github.com/littletof/prettyBenching) is a module, that aims to improve your benchmarking experience. It gives you an improved and customizable benchmarking progress and results in the terminal, enables you to easily track your results historically and to generate a full markdown report from your results.
=> Add prettyBenching to modules

README.md
I developed the GitHub Profile Trophy using Deno.
https://github.com/ryo-ma/github-profile-trophy
Original services using Deno are currently rare.
=> Add GitHub Profile Trophy to Showcases

README.md
[Lume](https://github.com/lumeland/lume) is a static site generator that can be used as a substitute for Jekyll or Eleventy.
=> Add lume to the list of tools

README.md
[oak-http-proxy](https://github.com/asos-craigmorten/oak-http-proxy) - Proxy middleware for Deno Oak HTTP servers.
=> Add oak-http-proxy

README.md
[opine-http-proxy](https://github.com/asos-craigmorten/opine-http-proxy) - Proxy middleware for Deno Opine HTTP servers.
=> Add opine-http-proxy

README.md
Hello Dear Deno Contributors, yesterday I created a telegram bot that can give details about updates of deno. Also, on inline mode it searches third party modules and routes to deno.land/x/package. On upcoming features, I want to cover doc routes and all other api of deno. I'd be very thankful if you confirm my request. Thanks for your attention)
=> Telegram Bot Assistant

README.md
[obsidian](https://github.com/oslabs-beta/obsidian) is Deno's first native GraphQL caching client and server module
=> Add obsidian module

.github/workflows/ci.yml
https://www.soubai.me/posts/create-interactive-mail-utility-cli-with-deno
This page includes some broken image references, and probably that causes the ci error.
This PR adds it to url-check whitelist to prevent the CI error.
=> Add www.soubai.me to whitelist

README.md
Dragon is a simple, fast and low HTTP router and URL matcher for building Deno servers. If you need performance and good productivity, you will love it.
=> Add dragon HTTP router and URL matcher f

README.md
**Link**: https://github.com/deno-libs/forwarded
**Description**: This is a Deno port of [forwarded](https://github.com/jshttp/forwarded/) library, which is used by Express. The library's utility is parsing `X-Forwarded-For` header.
Test coverage is 100%, API docs are in readme
=> Add "forwarded"

README.md
**Link**: https://github.com/deno-libs/graphql-tag
**Description**: this is a Deno port of a [graphql-tag](https://github.com/apollographql/graphql-tag) library, often used to create typedefs that get consumed by `makeExecutableSchema`.
as other libraries I submitted, this one has a few tests and autogenerated docs
=> Add graphql-tag

README.md
This reverts commit 7f94f5186c44de5f19cc97229198c01c0790fdc4 as the source code is no longer available.
=> Revert "Telegram Bot Assistant (#159)"

README.md
tincan is a Jest-like testing library that wraps `Deno.test`.
[Repo](https://github.com/gcaptn/tincan#readme)
=> Add tincan to modules

README.md
Module name is actually just [MaxmindDb](https://deno.land/x/maxminddb@v1.2.0/mod.ts) even though the github path is maxminddb-deno.
=> Add MaxmindDB

README.md
Repo link: https://github.com/deno-libs/superfetch
Description:
superfetch is a Superdeno-like superagent testing library based on Fetch API, ported from node-supertest-fetch.
Example:
```js
import { describe, it, run } from 'https://deno.land/x/tincan/mod.ts'
import { App } from 'https://deno.land/x/tinyhttp@0.1.6/app.ts'
import { makeFetch } from 'https://deno.land/x/superfetch/mod.ts'
import { ServerRequest } from 'https://deno.land/std@0.97.0/http/server.ts'
describe('makeFetch', () => {
it('should work with tinyhttp', async () => {
const s = new App().use((req) => req.respond({ body: 'Hello World' }))
const fetch = makeFetch(s.attach as (req: ServerRequest) => void)
await fetch('/').expect('Hello World')
})
})
run()
```
=> Add superfetch

README.md
Link: https://github.com/deno-libs/compression
Description: `compression` is a Deno HTTP compression that can be used to enable gzip/deflate compression for serving static assets.
=> Add compression

README.md
A simple dvm for Linux/MacOS, implemented by shellscript. [https://github.com/ghosind/dvm](https://github.com/ghosind/dvm)
=> Add ghosind/dvm.

README.md
Additional context: [Denops](https://github.com/vim-denops/denops.vim) is a ecosystem to write vim/neovim plugins with deno. Some plugins are already made in Denops ( https://github.com/search?p=1&q=denops&type=Repositories ). For example, https://github.com/Shougo/ddc.vim is a vim plugin written in Denops that provides sub-plugin system that also can be written in Deno ( https://github.com/topics/ddc-vim ).
It should be a good illustration that Deno has power to construct plugin system, sometimes replacing Node.js, Lua, etc...
~I wish (and believe) more things will be added in Ecosystem section in the future, so I made a new section.~
EDIT: move it into modules/editor-framework
=> Add vim-denops/denops.vim in new section Ecosystems

README.md
Hey.
Looks like the sockets library has moved and changed name to wocket. Just a simple fix.
=> Fixing moved repository "sockets" to new location and name.

README.md
We will move to another domain for Deno korea. 
cc @disjukr
=> Remove denoland.kr

README.md
Simple command line utility for executing commands with one or more .env files. Written with Deno and installed using the `deno install` command - though binaries are also distributed via GitHub.
This is different to existing entries as it is intended to be used as a stand-alone command line utility and not imported as a library.
=> Add with-env

README.md
Hi,
Firstly, this is my first PR for this project so please feel free to point out if I've made any mistakes.
I've created this PR to add a link to a VSCode template that I created that helps to get up and running with Deno a little faster.
It can be found [here (Upstream)](https://git.twilsoft.uk/twilsoft/vscode-deno-starter) or [here (Github Mirror for availability)](https://github.com/twilsoft/vscode-deno-starter). The link I've included in the PR is the Github link for obvious reasons.
Thanks for your review.
=> Adds vscode-deno-start to tools list

README.md
Get time duration from a timestamp or a human-readable string and vice versa.
Repo: https://github.com/retraigo/duration.js
Docs: https://docs.nekooftheabyss.moe/duration
=> Add durationjs

README.md
DangoDB is a MongoDB ODM.
Repository: [dangoDB](https://github.com/oslabs-beta/dangoDB)
=> Add dangoDB

README.md
Add https://github.com/nekooftheabyss/bettermap
BetterMap is just an extension of the JavaScript `Map` with Array-like methods for easier data reduction.
Docs: https://doc.deno.land/https://deno.land/x/bettermap@v1.1.0/mod.ts
(Also updated `duration.js`' repo from `retraigo/duration.js` to `nekooftheabyss/duration.js`.)
=> Feat: Add BetterMap

README.md
- Add `retraigo/cubic-bezier`
- A module for getting an array of points in a cubic bezier curve or visualizing the curve with canvas. https://github.com/retraigo/cubic-bezier
- Fix URL of `bettermap`, `fortuna` and `durationjs`
- Give `durationjs` a better description
=> Add `retraigo/cubic-bezier`

README.md
The team at [Saleor Commerce](https://github.com/saleor) rebuilt the great [Deno Merch](https://github.com/denoland/merch) demo, only this time using the Saleor platform. Along with the original example, both showcases provide a good entry for building an e-commerce website with Deno/Fresh.
=> Add Saleor + Deno to Showcases

README.md
The article "Build A Simple Covid19 CLI Tool using Deno" has moved to a new subdomain.
=> Fixed broken link to loginradius.com

README.md
react-icons are built on top of react and did not work with preact.
this lib contains the same icons, but works in Deno fresh project.
=> add react-icons for fresh

README.md
Adds Tui (https://github.com/Im-Beast/deno_tui)
=> feat: add tui

README.md
I'm the maintainer of [la-classy](https://github.com/retraigo/la-classy) and [appraisal](https://github.com/retraigo/appraisal). 
I have updated the URLs and descriptions of the two libraries.
=> Update classy and vectorizer URLs and descriptions.

README.md
Hello maintainers,
If possible, I'd love to propose an addition to our awesome-deno list: `oak-routing-ctrl`: https://github.com/Thesephi/oak-routing-ctrl
I trust that the project README already explains itself, but a TL;DR version: this library provisions TypeScript Decorators allowing for easy scaffolding API services built with the `@oak/oak` framework (which is directly listed above in this same list).
If further info is needed please comment below. I'm happy to elaborate :)
Thank you all 🍻
=> Add oak-routing-ctrl

README.md
Add entry for `Deno Dig` tool, which is able to extract application code and npm packages from executables produced by `deno compile`.
=> Add Deno Dig to tools section
